- hosts: all
  become: yes
  tasks:
    - name: create the 'operator' user
      user: name=operator append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'operator' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'operator ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the operator user
      authorized_key: user=operator key="{{item}}"
      with_file:
        - ~/.ssh/aws.pub